mysql:
  host: "114.132.245.76"
  port: 3306
  user: "root"
  password: "123456"
  database: "gin-scaffold"

redis:
  host: "114.132.245.76"
  port: 6379
  password: "123456"
  db: 0

rabbitmq:
  host: "47.112.109.63"
  port: 5672
  user: "admin"
  password: "breelk"
  name:
    delayTest: "delay.test"

wxRobot:
  errorRobot: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=cedaa47c-a156-4a8b-a4c9-0d407900ea63"

fsRobot:
  errorRobot: "https://open.feishu.cn/open-apis/bot/v2/hook/2f8e0477-44d5-4172-becc-f2f4d5d37820"
  stockRobot: "https://open.feishu.cn/open-apis/bot/v2/hook/c491a832-4705-4773-9ae4-c4293b7e7238"
  newsRobot: "https://open.feishu.cn/open-apis/bot/v2/hook/352cff98-51cd-48ab-a523-0968f031f49d"

qny:
  accessKey: "ciIHqTlKU1AjyJK6kb4LCXlLzxxxxxxxxxx"
  secretKey: "7iomzYL4h2ytAZxCTStNPDvY4xxxxxxxxx"
  bucket: "woorho"
  qnyServer: "https://xxxxxxx.fun"

aliyun:

system:
  # 应用名称
  name: "linbe-scaffold"
  # 应用版本
  version: "1.0.0"
  port: 4001
  migration: true
  chrome: "msedge.exe"
  env: "dev"
#  env: "release"

job:
  jobStatus:
    examplejob: false
#    crawlerfutunn: true

  jobCron:
    examplejob: "*/10 * * * * *"
#    crawlerfutunn: ""

stock:
  etf:
    "513120": "港股创新药ETF"
    "513090": "香港证券ETF"
    "513220": "中概互联ETF"
    "159887": "美国50ETF"
    "520550": "港股红利低波ETF"
    "159529": "普标消费ETF"
  sh:
    "600872": "中炬高新"
    "601318": "中国平安"
  sz:
    "000858": "五粮液"
    "002213": "大为股份"
    "300301": "ST长方"