mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  database: "gin-scaffold"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 8

qwRobot:
  errorRobot: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=021f5843-7177-4097-a0e7-xxxxxxxxxxxxxxxxxxx"

qny:
  accessKey: "ciIHqTlKU1AjyJK6kb4LCXlLzxxxxxxxxxx"
  secretKey: "7iomzYL4h2ytAZxCTStNPDvY4xxxxxxxxx"
  bucket: "woorho"
  qnyServer: "https://xxxxxxx.fun"

system:
  # 应用名称
  name: "linbe-scaffold"
  # 应用版本
  version: "1.0.0"
  port: 8399
  migration: false
  env: "dev"
#  env: "release"

job:
  jobStatus:
    examplejob: false

  jobCron:
    examplejob: "*/10 * * * * *"
