package thepaper

type ThePaper struct {
	Props struct {
		PageProps struct {
			Data struct {
				Code int `json:"code"`
				Data struct {
					HasNext   bool  `json:"hasNext"`
					StartTime int64 `json:"startTime"`
					List      []struct {
						ContId          string `json:"contId"`
						IsOutForword    string `json:"isOutForword"`
						IsOutForward    string `json:"isOutForward"`
						ForwardType     string `json:"forwardType"`
						MobForwardType  int    `json:"mobForwardType"`
						InteractionNum  string `json:"interactionNum"`
						PraiseTimes     string `json:"praiseTimes"`
						Pic             string `json:"pic"`
						ImgCardMode     int    `json:"imgCardMode"`
						SmallPic        string `json:"smallPic"`
						SharePic        string `json:"sharePic"`
						PubTime         string `json:"pubTime"`
						PubTimeNew      string `json:"pubTimeNew"`
						Name            string `json:"name"`
						CornerLabelDesc string `json:"cornerLabelDesc,omitempty"`
						ClosePraise     string `json:"closePraise"`
						NodeInfo        struct {
							NodeId                  int    `json:"nodeId"`
							Name                    string `json:"name"`
							Desc                    string `json:"desc"`
							Pic                     string `json:"pic"`
							NodeType                int    `json:"nodeType"`
							ChannelType             int    `json:"channelType"`
							ForwordType             int    `json:"forwordType"`
							ForwardType             string `json:"forwardType"`
							LiveType                string `json:"liveType"`
							ParentId                int    `json:"parentId"`
							IsOrder                 string `json:"isOrder"`
							DataType                string `json:"dataType"`
							ShareName               string `json:"shareName"`
							NickName                string `json:"nickName"`
							PublishTime             int64  `json:"publishTime"`
							MobForwardType          string `json:"mobForwardType"`
							Summarize               string `json:"summarize"`
							Color                   string `json:"color"`
							VideoLivingRoomDes      string `json:"videoLivingRoomDes"`
							WwwSpecNodeAlign        int    `json:"wwwSpecNodeAlign"`
							GovAffairsType          string `json:"govAffairsType"`
							ShowSpecialBanner       bool   `json:"showSpecialBanner"`
							ShowSpecialTopDesc      bool   `json:"showSpecialTopDesc"`
							TopBarTypeCustomColor   bool   `json:"topBarTypeCustomColor"`
							ShowVideoBottomRightBtn bool   `json:"showVideoBottomRightBtn"`
							RecommendIds            []int  `json:"recommendIds,omitempty"`
						} `json:"nodeInfo"`
						NodeId            int    `json:"nodeId"`
						ContType          int    `json:"contType"`
						PubTimeLong       int64  `json:"pubTimeLong"`
						SpecialNodeId     int    `json:"specialNodeId"`
						CardMode          string `json:"cardMode"`
						DataObjId         int    `json:"dataObjId"`
						CloseFrontComment bool   `json:"closeFrontComment"`
						IsSupInteraction  bool   `json:"isSupInteraction"`
						TagList           []struct {
							TagId               int    `json:"tagId"`
							Tag                 string `json:"tag"`
							IsOrder             string `json:"isOrder"`
							IsUpdateNotify      string `json:"isUpdateNotify"`
							IsWonderfulComments string `json:"isWonderfulComments"`
						} `json:"tagList"`
						HideVideoFlag  bool `json:"hideVideoFlag"`
						PraiseStyle    int  `json:"praiseStyle"`
						IsSustainedFly int  `json:"isSustainedFly"`
						SoftLocType    int  `json:"softLocType"`
						CloseComment   bool `json:"closeComment"`
						VoiceInfo      struct {
							VoiceSrc    string `json:"voiceSrc,omitempty"`
							ImgSrc      string `json:"imgSrc"`
							IsHaveVoice string `json:"isHaveVoice"`
						} `json:"voiceInfo"`
						SoftAdTypeStr         string `json:"softAdTypeStr"`
						OriginalContId        int    `json:"originalContId"`
						Paywalled             bool   `json:"paywalled"`
						AudiovisualBlogSwitch bool   `json:"audiovisualBlogSwitch"`
						AudiovisualBlogGuests string `json:"audiovisualBlogGuests"`
						SeriesTagRecType      string `json:"seriesTagRecType"`
						WaterMark             struct {
							Type        string `json:"type"`
							Value       string `json:"value"`
							BigPicValue string `json:"bigPicValue"`
							VideoSize   string `json:"videoSize,omitempty"`
						} `json:"waterMark,omitempty"`
						Videos struct {
							VideoId            interface{} `json:"videoId"`
							Hdurl              string      `json:"hdurl"`
							Url                string      `json:"url"`
							Duration           string      `json:"duration"`
							CoverUrl           string      `json:"coverUrl"`
							VerticalCoverUrl   string      `json:"verticalCoverUrl"`
							Bytes              string      `json:"bytes"`
							HdBytes            string      `json:"hdBytes"`
							CoverUrlFirstFrame string      `json:"coverUrlFirstFrame"`
							VerticalVideo      bool        `json:"verticalVideo"`
							DurationNum        int         `json:"durationNum"`
							VideoDes           interface{} `json:"videoDes"`
							PlayInfos          interface{} `json:"playInfos"`
							OutLink            bool        `json:"outLink"`
						} `json:"videos,omitempty"`
					} `json:"list"`
					NodeInfo struct {
						NodeId                  int    `json:"nodeId"`
						Name                    string `json:"name"`
						Desc                    string `json:"desc"`
						NodeType                int    `json:"nodeType"`
						ChannelType             int    `json:"channelType"`
						ForwordType             int    `json:"forwordType"`
						ForwardType             string `json:"forwardType"`
						LiveType                string `json:"liveType"`
						ParentId                int    `json:"parentId"`
						BigDataCode             string `json:"bigDataCode"`
						IsOrder                 string `json:"isOrder"`
						DataType                string `json:"dataType"`
						ShareName               string `json:"shareName"`
						ChannelId               int    `json:"channelId"`
						NickName                string `json:"nickName"`
						PublishTime             int64  `json:"publishTime"`
						MobForwardType          string `json:"mobForwardType"`
						Summarize               string `json:"summarize"`
						Color                   string `json:"color"`
						VideoLivingRoomDes      string `json:"videoLivingRoomDes"`
						WwwSpecNodeAlign        int    `json:"wwwSpecNodeAlign"`
						GovAffairsType          string `json:"govAffairsType"`
						ShowSpecialBanner       bool   `json:"showSpecialBanner"`
						ShowSpecialTopDesc      bool   `json:"showSpecialTopDesc"`
						TopBarTypeCustomColor   bool   `json:"topBarTypeCustomColor"`
						ShowVideoBottomRightBtn bool   `json:"showVideoBottomRightBtn"`
					} `json:"nodeInfo"`
					TagInfo        interface{} `json:"tagInfo"`
					MoreNodeInfo   interface{} `json:"moreNodeInfo"`
					PageNum        int         `json:"pageNum"`
					PageSize       int         `json:"pageSize"`
					Pages          interface{} `json:"pages"`
					Total          interface{} `json:"total"`
					PrevPageNum    interface{} `json:"prevPageNum"`
					NextPageNum    interface{} `json:"nextPageNum"`
					ExcludeContIds interface{} `json:"excludeContIds"`
					ContCont       interface{} `json:"contCont"`
					FilterIds      interface{} `json:"filterIds"`
					UpdateCount    interface{} `json:"updateCount"`
				} `json:"data"`
				Desc string `json:"desc"`
				Time int64  `json:"time"`
			} `json:"data"`
			TopData struct {
				Code int `json:"code"`
				Data struct {
					RecommendTxt [][]interface{} `json:"recommendTxt"`
					RecommendImg []struct {
						ContId          string `json:"contId"`
						IsOutForword    string `json:"isOutForword"`
						IsOutForward    string `json:"isOutForward"`
						ForwardType     string `json:"forwardType"`
						MobForwardType  int    `json:"mobForwardType"`
						InteractionNum  string `json:"interactionNum"`
						PraiseTimes     string `json:"praiseTimes"`
						Pic             string `json:"pic"`
						ImgCardMode     int    `json:"imgCardMode"`
						SmallPic        string `json:"smallPic"`
						SharePic        string `json:"sharePic"`
						PubTime         string `json:"pubTime"`
						PubTimeNew      string `json:"pubTimeNew"`
						Name            string `json:"name"`
						CornerLabelDesc string `json:"cornerLabelDesc"`
						ClosePraise     string `json:"closePraise"`
						NodeInfo        struct {
							NodeId                  int    `json:"nodeId"`
							Name                    string `json:"name"`
							Desc                    string `json:"desc"`
							Pic                     string `json:"pic"`
							NodeType                int    `json:"nodeType"`
							ChannelType             int    `json:"channelType"`
							ForwordType             int    `json:"forwordType"`
							ForwardType             string `json:"forwardType"`
							LiveType                string `json:"liveType"`
							ParentId                int    `json:"parentId"`
							IsOrder                 string `json:"isOrder"`
							DataType                string `json:"dataType"`
							ShareName               string `json:"shareName"`
							NickName                string `json:"nickName"`
							PublishTime             int64  `json:"publishTime"`
							MobForwardType          string `json:"mobForwardType"`
							Summarize               string `json:"summarize"`
							Color                   string `json:"color"`
							VideoLivingRoomDes      string `json:"videoLivingRoomDes"`
							WwwSpecNodeAlign        int    `json:"wwwSpecNodeAlign"`
							GovAffairsType          string `json:"govAffairsType"`
							ShowSpecialBanner       bool   `json:"showSpecialBanner"`
							ShowSpecialTopDesc      bool   `json:"showSpecialTopDesc"`
							TopBarTypeCustomColor   bool   `json:"topBarTypeCustomColor"`
							ShowVideoBottomRightBtn bool   `json:"showVideoBottomRightBtn"`
						} `json:"nodeInfo"`
						NodeId            int    `json:"nodeId"`
						ContType          int    `json:"contType"`
						PubTimeLong       int64  `json:"pubTimeLong"`
						SpecialNodeId     int    `json:"specialNodeId"`
						CardMode          string `json:"cardMode"`
						DataObjId         int    `json:"dataObjId"`
						CloseFrontComment bool   `json:"closeFrontComment"`
						IsSupInteraction  bool   `json:"isSupInteraction"`
						TagList           []struct {
							TagId               int    `json:"tagId"`
							Tag                 string `json:"tag"`
							IsOrder             string `json:"isOrder"`
							IsUpdateNotify      string `json:"isUpdateNotify"`
							IsWonderfulComments string `json:"isWonderfulComments"`
						} `json:"tagList"`
						HideVideoFlag  bool `json:"hideVideoFlag"`
						PraiseStyle    int  `json:"praiseStyle"`
						IsSustainedFly int  `json:"isSustainedFly"`
						SoftLocType    int  `json:"softLocType"`
						CloseComment   bool `json:"closeComment"`
						VoiceInfo      struct {
							VoiceSrc    string `json:"voiceSrc"`
							ImgSrc      string `json:"imgSrc"`
							IsHaveVoice string `json:"isHaveVoice"`
						} `json:"voiceInfo"`
						SoftAdTypeStr         string `json:"softAdTypeStr"`
						OriginalContId        int    `json:"originalContId"`
						Paywalled             bool   `json:"paywalled"`
						AudiovisualBlogSwitch bool   `json:"audiovisualBlogSwitch"`
						AudiovisualBlogGuests string `json:"audiovisualBlogGuests"`
						SeriesTagRecType      string `json:"seriesTagRecType"`
					} `json:"recommendImg"`
					NodeInfo struct {
						NodeId                  int    `json:"nodeId"`
						Name                    string `json:"name"`
						Desc                    string `json:"desc"`
						NodeType                int    `json:"nodeType"`
						ChannelType             int    `json:"channelType"`
						ForwordType             int    `json:"forwordType"`
						ForwardType             string `json:"forwardType"`
						LiveType                string `json:"liveType"`
						ParentId                int    `json:"parentId"`
						IsOrder                 string `json:"isOrder"`
						DataType                string `json:"dataType"`
						ShareName               string `json:"shareName"`
						NickName                string `json:"nickName"`
						PublishTime             int64  `json:"publishTime"`
						MobForwardType          string `json:"mobForwardType"`
						Summarize               string `json:"summarize"`
						Color                   string `json:"color"`
						VideoLivingRoomDes      string `json:"videoLivingRoomDes"`
						WwwSpecNodeAlign        int    `json:"wwwSpecNodeAlign"`
						GovAffairsType          string `json:"govAffairsType"`
						ShowSpecialBanner       bool   `json:"showSpecialBanner"`
						ShowSpecialTopDesc      bool   `json:"showSpecialTopDesc"`
						TopBarTypeCustomColor   bool   `json:"topBarTypeCustomColor"`
						ShowVideoBottomRightBtn bool   `json:"showVideoBottomRightBtn"`
					} `json:"nodeInfo"`
					ExcludeContIds           []int       `json:"excludeContIds"`
					ListRecommendIds         []int       `json:"listRecommendIds"`
					FinancialInformationNews interface{} `json:"financialInformationNews"`
					NoImgRecommend           bool        `json:"noImgRecommend"`
				} `json:"data"`
				Desc string `json:"desc"`
				Time int64  `json:"time"`
			} `json:"topData"`
			Province interface{} `json:"province"`
			Id       string      `json:"id"`
		} `json:"pageProps"`
		NSSP bool `json:"__N_SSP"`
	} `json:"props"`
	Page  string `json:"page"`
	Query struct {
		Id string `json:"id"`
	} `json:"query"`
	BuildId      string        `json:"buildId"`
	IsFallback   bool          `json:"isFallback"`
	Gssp         bool          `json:"gssp"`
	ScriptLoader []interface{} `json:"scriptLoader"`
}
